### ISSUE TITLE
Shopping Cart status

### ISSUE THREAD

**Issue by minkhaaa** [1awlet/Unique-Garments-website-Group-project-#14]
A user pointed out that shopping cart should reflect/response in some way about an item being added to the cart successfully during add to cart operation. It would be a great addition for our system's improvement. 

![Screenshot 2023-09-11 at 8 45 52 PM](https://github.com/gelehasan/Unique-Garments-website-Group-project-/assets/102034245/a0525985-1855-456a-bf5c-27e37ec3e2b5)

**Comment by gelehasan** [comment]
Thank you Minkha, its a great future and I will definitely add it, so you can already start by writing that we implemented this future
